#We want to present the number of CUSTOMER( COUNT(*)) that a dealer has, the total sales (SUM(PRICE)) for each dealer and (DEALERS_NAME) 

CREATE MATERIALIZED  VIEW QUERY1 AS(
SELECT COUNT(*) AS TOTAL_CUSTOMER_PER_DEALER,SUM(PRICE) AS TOTAL_SALES_PER_DEALER, D.DEALERS_NAME FROM CUSTOMER AS C
INNER JOIN RECORD AS R
ON R.CID = C.CID
INNER JOIN DEALER AS D
ON D.DID  = R.DID
GROUP BY D.DEALERS_NAME
)

SELECT * FROM QUERY1
	
# We want to present the CUSTOMERS NAME, his VIN and MODEL NAME the CORRESPONDING BRAND AND their EXTRAS

CREATE VIEW QUERY2 AS(
SELECT CUST.NAME,V.VIN, V.MODEL_NAME, V.vehicle_brand, AUTO, EXTRA_HORSE_POWER 
FROM CUSTOMER AS CUST
INNER JOIN VEHICLE AS V
ON CUST.CID= V.OWNER_ID
INNER JOIN EXTRAS AS EX
ON EX.EXTRAS_ID = V.EXTRAS_ID
)
CREATE UNIQUE INDEX 
    DEALERS_NAME
ON QUERY1(DEALERS_NAME);

SELECT * FROM QUERY2